apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
data:
  haproxy.cfg: |
    global
      daemon
      maxconn 256

    defaults
      mode http
      timeout connect 5000ms
      timeout client 50000ms
      timeout server 50000ms

    frontend http-in
      bind *:80
      default_backend web-servers

    backend web-servers
      balance roundrobin
{{- range $index, $server := .Values.backendServers }}
      server web{{ $index }} {{ $server.ip }}:80 check
{{- end }}
