apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  type: {{ .Values.service.kafka.type }}
  ports:
    - port: {{ .Values.kafka.port }}
      targetPort: {{ .Values.kafka.port }}
  selector:
    app: kafka
