apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  type: {{ .Values.service.kafka.type }}
  loadBalancerIP: {{ .Values.service.kafka.loadBalancerIP }}
  ports:
    - name: internal
      port: {{ .Values.kafka.port }}
      targetPort: {{ .Values.kafka.port }}
    - name: external
      port: {{ .Values.kafka.externalPort }}
      targetPort: {{ .Values.kafka.externalPort }}
  selector:
    app: kafka