apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.kafka.zookeeperPort }}
      targetPort: {{ .Values.kafka.zookeeperPort }}
  selector:
    app: zookeeper
