kafka:
  image: bitnami/kafka:3.7.0
  zookeeperImage: bitnami/zookeeper:3.8
  port: 9092
  zookeeperPort: 2181
  clusterIP: None

  config:
    KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
    KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka.default.svc.cluster.local:9092
    KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
    KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ALLOW_PLAINTEXT_LISTENER: "yes"

manager:
  image: bdorado/nfvsec-manager
  port: 8000
  env:
    BROKER_ADDRESS: kafka:9092

service:
  kafka:
    type: ClusterIP
  manager:
    type: LoadBalancer
