apiVersion: v1
kind: Pod
metadata:
  name: haproxy-lb
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      [{
        "name": "{{ .Values.network.name }}",
        "interface": "net1",
        "ips": ["{{ .Values.network.ip }}{{ .Values.network.subnetMask }}"]
      }]
spec:
  nodeSelector:
    {{- toYaml .Values.nodeSelector | nindent 4 }}
  containers:
    - name: haproxy
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      volumeMounts:
        - name: haproxy-conf
          mountPath: /usr/local/etc/haproxy
      ports:
        - containerPort: 80

    - name: sec-agent
      image: "{{ .Values.secAgent.image }}"
      imagePullPolicy: Always
      env:
        - name: VNF_ID
          value: "{{ .Values.secAgent.vnfId }}"
        - name: BROKER_ADDRESS
          value: "{{ .Values.secAgent.brokerAddress }}"
        - name: PUBLIC_KEY
          value: "{{ .Values.secAgent.publicKey }}"
        - name: VNF_FG_TOPIC
          value: "{{ .Values.secAgent.fgTopic }}"
        - name: DECLARATION_TIMEOUT_MS
          value: "{{ .Values.secAgent.timeout }}"
        - name: PREFERRED_MECHANISMS
          value: "{{ .Values.secAgent.mechanisms }}"
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
  
  volumes:
    - name: haproxy-conf
      configMap:
        name: haproxy-config
