apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: access-l2-net
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "bridge",
      "bridge": "br-access",
      "isGateway": true,
      "ipam": {
        "type": "static",
        "subnet": "10.98.0.0/24",
        "gateway": "10.98.0.1",
        "routes": [
          {
            "dst": "10.78.0.0/24",
            "gw": "10.98.0.12"
          },
          {
            "dst": "10.88.0.0/24",
            "gw": "10.98.0.12"
          }
        ]
      }
    }
