apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: transport-net
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "bridge",
      "bridge": "br-transport",
      "isGateway": true,
      "ipam": {
        "type": "static",
        "subnet": "10.88.0.0/24",
        "gateway": "10.88.0.1"
      }
    }
