apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ .Values.network.name }}
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "bridge",
      "bridge": "{{ .Values.network.bridge }}",
      "isGateway": true,
      "ipam": {
        "type": "static",
        "subnet": "{{ .Values.network.subnet }}",
        "gateway": "{{ .Values.network.gateway }}",
        "routes": [
          {{- range $index, $route := .Values.network.routes }}
          {{- if $index }},{{ end }}
          {
            "dst": "{{ $route.dst }}",
            "gw": "{{ $route.gw }}"
          }
          {{- end }}
        ]
      }
    }
