{{- range .Values.servers }}
apiVersion: v1
kind: Pod
metadata:
  name: {{ .name }}
  labels:
    app: web
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      [{
        "name": "{{ $.Values.network.name }}",
        "interface": "net1",
        "ips": ["{{ .ip }}/24"]
      }]
spec:
  nodeSelector:
    {{- toYaml $.Values.nodeSelector | nindent 4 }}
  containers:
    - name: web-server
      image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
      imagePullPolicy: {{ $.Values.image.pullPolicy }}
      securityContext:
        privileged: true
      ports:
        - containerPort: 80

    - name: sec-agent
      image: "{{ $.Values.secAgent.image }}"
      imagePullPolicy: Always
      env:
        - name: VNF_ID
          value: "{{ .vnfId }}"
        - name: BROKER_ADDRESS
          value: "{{ $.Values.secAgent.brokerAddress }}"
        - name: PUBLIC_KEY
          value: "{{ .publicKey }}"
        - name: VNF_FG_TOPIC
          value: "{{ $.Values.secAgent.fgTopic }}"
        - name: DECLARATION_TIMEOUT_MS
          value: "{{ $.Values.secAgent.timeout }}"
        - name: PREFERRED_MECHANISMS
          value: "{{ $.Values.secAgent.mechanisms }}"
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
---
{{- end }}

